import { Screen } from "navigation.slint";
import { TranslationScreen } from "translation-screen.slint";
import { NoLanguagesScreen } from "no-languages-screen.slint";
import { SettingsScreen } from "settings-screen.slint";
import { ManageLanguagesScreen } from "manage-languages-screen.slint";
import { Language } from "language.slint";
import { AppTheme } from "theme.slint";

export component AppWindow inherits Window {
    title: "Offline Translator";
    background: AppTheme.background;
    min-width: 600px;
    preferred-width: 600px;
    preferred-height: 800px;
    icon: @image-url("../assets/logo.svg");

    out property <bool> has-languages: all-installed-languages.length > 1; // english
    in-out property <Screen> current-screen;
    in property <Language> source-language;
    in property <Language> target-language;
    out property <string> input-text;
    in property <string> output-text;
    in property <Language> detected-language;

    in property <[Language]> all-languages;
    in property <[Language]> all-installed-languages;
    in property <[Language]> not-installed-languages;
    in property <[Language]> installed-from-languages;
    in property <[Language]> installed-to-languages;

    in property <[string]> installed-from-language-names; // hack, combobox should take model
    in property <[string]> installed-to-language-names;

    in property <image> swap-icon: @image-url("../assets/swap.svg");
    in property <image> settings-icon: @image-url("../assets/settings.svg");
    in property <image> camera-icon: @image-url("../assets/camera.svg");
    in property <image> back-icon: @image-url("../assets/back.svg");
    in property <image> download-icon: @image-url("../assets/download.svg");
    in property <image> delete-icon: @image-url("../assets/delete.svg");
    in property <image> forward-icon: @image-url("../assets/forward.svg");

    // events
    callback language-downloaded(string);
    callback download-progress(string, float);
    callback languages-cleared();

    // inputs
    callback swap-languages();
    callback camera-clicked();
    callback process-text(string);
    callback download-language(Language);
    callback delete-language(Language);
    callback set-from(string);
    callback set-to(string);

    if current-screen == Screen.NoLanguages: NoLanguagesScreen {
        width: 100%;
        height: 100%;
        settings-icon: root.settings-icon;
        download-icon: root.download-icon;
        delete-icon: root.delete-icon;
        installed-languages: root.all-installed-languages;
        not-installed-languages: root.not-installed-languages;

        settings-clicked => {
            root.current-screen = Screen.Settings;
        }
        download-language(lang) => {
            root.download-language(lang);
        }
        delete-language(lang) => {
            root.delete-language(lang);
        }
        done-clicked => {
            root.current-screen = Screen.Translation;
        }
    }

    if current-screen == Screen.Translation: TranslationScreen {
        width: 100%;
        height: 100%;
        source-language: root.source-language;
        target-language: root.target-language;
        detected-language: root.detected-language;
        input-text <=> root.input-text;
        output-text: root.output-text;
        installed-languages: root.all-installed-languages;
        installed-from-language-names: root.installed-from-language-names;
        installed-to-language-names: root.installed-to-language-names;
        swap-icon: root.swap-icon;
        settings-icon: root.settings-icon;
        camera-icon: root.camera-icon;
        forward-icon: root.forward-icon;
        download-icon: root.download-icon;

        download-language(lang) => {
            root.download-language(lang)
        }
        swap-languages => {
            root.swap-languages();
        }
        settings-clicked => {
            root.current-screen = Screen.Settings;
        }
        camera-clicked => {
            root.camera-clicked();
        }
        text-changed => {
            root.process-text(root.input-text);
        }
        set-from(name) => {
            root.set-from(name);
        }
        set-to(name) => {
            root.set-to(name);
        }
    }

    if current-screen == Screen.Settings: SettingsScreen {
        width: 100%;
        height: 100%;
        back-icon: root.back-icon;
        back-clicked => {
            root.current-screen = Screen.Translation;
        }
    }

    if current-screen == Screen.ManageLanguages: ManageLanguagesScreen {
        width: 100%;
        height: 100%;
        back-icon: root.back-icon;
        download-icon: root.download-icon;
        delete-icon: root.delete-icon;
        installed-languages: root.all-installed-languages;
        not-installed-languages: root.not-installed-languages;

        back-clicked => {
            root.current-screen = root.has-languages ? Screen.Translation : Screen.NoLanguages;
        }
        download-language(lang) => {
            root.download-language(lang);
        }
        delete-language(lang) => {
            root.delete-language(lang);
        }
    }
}
