import { Screen } from "navigation.slint";
import { TranslationScreen } from "translation-screen.slint";
import { NoLanguagesScreen } from "no-languages-screen.slint";
import { SettingsScreen } from "settings-screen.slint";
import { ManageLanguagesScreen } from "manage-languages-screen.slint";
import { AppTheme } from "theme.slint";

export component AppWindow inherits Window {
    title: "Offline Translator";
    background: AppTheme.background;
    preferred-width: 500px;
    preferred-height: 800px;

    in-out property <bool> has-languages: false;
    in-out property <Screen> current-screen: has-languages ? Screen.Translation : Screen.NoLanguages;

    in-out property <string> source-language: "Dutch";
    in-out property <string> target-language: "English";
    in-out property <string> input-text;
    in-out property <string> output-text;

    in property <image> swap-icon: @image-url("../assets/swap.svg");
    in property <image> settings-icon: @image-url("../assets/settings.svg");
    in property <image> history-icon: @image-url("../assets/history.svg");
    in property <image> camera-icon: @image-url("../assets/camera.svg");
    in property <image> back-icon: @image-url("../assets/back.svg");

    callback swap-languages();
    callback history-clicked();
    callback camera-clicked();
    callback process-text(string) -> string;

    if current-screen == Screen.NoLanguages: NoLanguagesScreen {
        width: 100%;
        height: 99%;
        manage-languages-clicked => {
            root.current-screen = Screen.ManageLanguages;
        }
    }

    if current-screen == Screen.Translation: TranslationScreen {
        width: 100%;
        height: 100%;
        source-language <=> root.source-language;
        target-language <=> root.target-language;
        input-text <=> root.input-text;
        output-text <=> root.output-text;
        swap-icon: root.swap-icon;
        settings-icon: root.settings-icon;
        history-icon: root.history-icon;
        camera-icon: root.camera-icon;

        swap-languages => {
            root.swap-languages();
        }
        settings-clicked => {
            root.current-screen = Screen.Settings;
        }
        history-clicked => {
            root.history-clicked();
        }
        camera-clicked => {
            root.camera-clicked();
        }
        text-changed => {
            root.output-text = root.process-text(root.input-text);
        }
    }

    if current-screen == Screen.Settings: SettingsScreen {
        width: 100%;
        height: 100%;
        back-icon: root.back-icon;
        back-clicked => {
            root.current-screen = Screen.Translation;
        }
    }

    if current-screen == Screen.ManageLanguages: ManageLanguagesScreen {
        width: 100%;
        height: 100%;
        back-icon: root.back-icon;
        back-clicked => {
            root.current-screen = root.has-languages ? Screen.Translation : Screen.NoLanguages;
        }
    }
}
