import { Language } from "language.slint";
import { IconButton } from "icon-button.slint";
import { AppTheme } from "theme.slint";

export component LanguageItem {
    in property <Language> language;
    in property <bool> is-installed: false;
    in property <image> download-icon;
    in property <image> delete-icon;

    callback action-clicked();

    // height: 64px;

    Rectangle {
        HorizontalLayout {
            spacing: 16px;

            VerticalLayout {
                alignment: center;
                spacing: 4px;
                horizontal-stretch: 1;

                Text {
                    text: language.name;
                    font-size: 16px;
                    color: AppTheme.text-primary;
                    horizontal-alignment: left;
                }

                Text {
                    text: language.size;
                    font-size: 14px;
                    color: AppTheme.text-secondary;
                    horizontal-alignment: left;
                }
            }

            IconButton {
                icon: is-installed ? root.delete-icon : root.download-icon;
                size: 24px;
                clicked => {
                    root.action-clicked();
                }
            }
        }
    }
}
