import { Language } from "language.slint";
import { IconButton } from "icon-button.slint";
import { AppTheme } from "theme.slint";
import { Spinner } from "std-widgets.slint";

export component LanguageItem {
    in property <Language> language;
    in property <bool> is-installed: false;
    in property <image> delete-icon: @image-url("assets/delete.svg");
    in property <image> download-icon: @image-url("assets/download.svg");

    callback action-clicked();
    Rectangle {
        HorizontalLayout {
            spacing: 16px;

            VerticalLayout {
                alignment: center;
                spacing: 4px;
                horizontal-stretch: 1;

                Text {
                    text: language.name;
                    font-size: 16px;
                    color: AppTheme.text-primary;
                    horizontal-alignment: left;
                }

                Text {
                    text: language.code == "en" ? "Built in" : language.size;
                    font-size: 14px;
                    color: AppTheme.text-secondary;
                    horizontal-alignment: left;
                }
            }

            if root.language.download-progress > 0: Spinner {
                progress: root.language.download-progress;
                indeterminate: false;
            }
            if root.language.download-progress == 0: IconButton {
                icon: root.is-installed ? root.delete-icon : root.download-icon;
                size: 24px;
                enabled: language.code != "en";
                clicked => {
                    root.action-clicked();
                }
            }
        }
    }
}
