import { ComboBox } from "std-widgets.slint";
import { AppTheme } from "theme.slint";
import { Language } from "language.slint";

export component LanguageSelector {
    in property <Language> current-language;
    in property <[string]> language-names;
    callback language-selected(string);

    HorizontalLayout {
        padding: 4px;

        ComboBox {
            current-value: root.current-language.name;
            model: root.language-names;
            selected(value) => {
                root.language-selected(value);
            }
        }
    }
}
