import { Language } from "language.slint";
import { IconButton } from "icon-button.slint";
import { AppTheme } from "theme.slint";
import { Spinner } from "std-widgets.slint";

export component MissingLanguageCard {
    in property <Language> language;
    in property <image> download-icon: @image-url("assets/download.svg");
    in property <image> forward-icon: @image-url("assets/forward.svg");

    callback action-clicked();

    Rectangle {
        background: AppTheme.surface;
        border-radius: 12px;

        HorizontalLayout {
            padding: 20px;
            spacing: 16px;

            VerticalLayout {
                alignment: center;
                spacing: 2px;
                horizontal-stretch: 1;

                Text {
                    text: language.installed ? "Translate from" : "Missing language";
                    font-size: 14px;
                    color: AppTheme.text-secondary;
                    horizontal-alignment: left;
                }

                Text {
                    text: language.name;
                    font-size: 18px;
                    color: AppTheme.text-primary;
                    horizontal-alignment: left;
                }
            }

            if root.language.download-progress > 0: Spinner {
                progress: root.language.download-progress;
                indeterminate: false;
            }
            if root.language.download-progress == 0: IconButton {
                icon: language.installed ? root.forward-icon : root.download-icon;
                enabled: true;
                size: 24px;
                clicked => {
                    root.action-clicked();
                }
            }
        }
    }
}
