import { IconButton } from "icon-button.slint";
import { Button } from "button.slint";
import { LabeledCheckbox } from "labeled-checkbox.slint";
import { AppTheme } from "theme.slint";

export component SettingsScreen {
    in property <image> back-icon;
    in-out property <bool> disable-auto-detect;

    callback back-clicked();
    callback manage-languages-clicked();

    Rectangle {
        background: AppTheme.background;

        VerticalLayout {
            HorizontalLayout {
                padding: 4px;
                IconButton {
                    icon: root.back-icon;
                    size: 24px;
                    clicked => {
                        root.back-clicked();
                    }
                }

                Text {
                    text: "Settings";
                    font-size: 20px;
                    color: AppTheme.text-primary;
                    vertical-alignment: center;
                    horizontal-stretch: 1;
                }
            }

            Rectangle {
                height: 1px;
                background: AppTheme.border;
            }

            VerticalLayout {
                padding: 16px;
                spacing: 16px;
                alignment: LayoutAlignment.start;

                Button {
                    label: "Manage languages";
                    clicked => {
                        root.manage-languages-clicked();
                    }
                }

                LabeledCheckbox {
                    label: "Disable automatic language detection";
                    checked <=> root.disable-auto-detect;
                }
            }
        }
    }
}
