import { AppTheme } from "theme.slint";
import { TextEdit, ScrollView } from "std-widgets.slint";

export component TextInputArea inherits ScrollView {
    in-out property <string> text;
    in property <string> placeholder-text: "Enter text";
    callback changed();

    forward-focus: input;
    VerticalLayout {

        input := TextInput {
            single-line: false;
            text <=> root.text;
            font-size: 16px;
            wrap: word-wrap;
            color: AppTheme.text-primary;
            edited => {
                root.changed();
                root.viewport-y = root.viewport-height;
            }
        }
    }
}
