import { TextEdit, ScrollView } from "std-widgets.slint";
import { AppTheme } from "theme.slint";

export component TextInputArea inherits ScrollView {
    in-out property <string> text;
    in property <string> placeholder-text: "Enter text";
    callback changed();

    forward-focus: input;
    VerticalLayout {
        padding-left: 16px;
        padding-right: 16px;
        input := TextInput {
            single-line: false;
            text <=> root.text;
            font-size: 16px;
            wrap: word-wrap;
            edited => {
                root.changed();
                root.viewport-y = root.viewport-height;
            }
        }
    }
}
