import { TextEdit } from "std-widgets.slint";
import { AppTheme } from "theme.slint";

export component TextInputArea {
    in-out property <string> text;
    in property <string> placeholder-text: "Enter text";
    callback changed();

    Rectangle {
        background: AppTheme.background;
        VerticalLayout {
            padding: 16px;
            TextInput {
                single-line: false;
                text <=> root.text;
                font-size: 16px;
                wrap: word-wrap;
                vertical-stretch: 1;
                edited => {
                    root.changed();
                }
            }
        }
    }
}
