import { LanguageSelector } from "language-selector.slint";
import { IconButton } from "icon-button.slint";
import { AppTheme } from "theme.slint";
import { Language } from "language.slint";

export component TopBar {
    in property <Language> source-language;
    in property <Language> target-language;
    in property <[string]> installed-from-language-names;
    in property <[string]> installed-to-language-names;

    in property <bool> swap-enabled;
    in property <image> swap-icon;
    in property <image> settings-icon;

    callback swap-languages();
    callback settings-clicked();
    callback set-from(string);
    callback set-to(string);

    Rectangle {
        background: AppTheme.background;

        HorizontalLayout {
            padding: 8px;
            spacing: 8px;

            LanguageSelector {
                current-language: root.source-language;
                language-names: root.installed-from-language-names;
                horizontal-stretch: 1;
                language-selected(name) => {
                    root.set-from(name);
                }
            }

            IconButton {
                icon: root.swap-icon;
                size: 20px;
                enabled: root.swap-enabled;
                clicked => {
                    root.swap-languages();
                }
            }

            LanguageSelector {
                current-language: root.target-language;
                language-names: root.installed-to-language-names;
                horizontal-stretch: 1;
                language-selected(name) => {
                    root.set-to(name);
                }
            }

            IconButton {
                icon: root.settings-icon;
                size: 20px;
                clicked => {
                    root.settings-clicked();
                }
            }
        }
    }
}
