import { TopBar } from "top-bar.slint";
import { TextInputArea } from "text-input-area.slint";
import { TranslationOutputArea } from "translation-output-area.slint";
import { FloatingActionButton } from "floating-action-button.slint";
import { AppTheme } from "theme.slint";
import { Language } from "language.slint";


export component TranslationScreen {
    in-out property <Language> source-language;
    in-out property <Language> target-language;
    in-out property <string> input-text;
    in-out property <string> output-text;

    in property <[Language]> installed-languages;
    in property <[string]> installed-language-names;
    in property <image> swap-icon;
    in property <image> settings-icon;
    in property <image> camera-icon;

    callback swap-languages();
    callback settings-clicked();
    callback camera-clicked();
    callback text-changed();
    callback set-from(string);
    callback set-to(string);

    VerticalLayout {
        TopBar {
            source-language: root.source-language;
            target-language: root.target-language;
            installed-languages: root.installed-languages;
            installed-language-names: root.installed-language-names;
            swap-icon: root.swap-icon;
            settings-icon: root.settings-icon;

            swap-languages => {
                root.swap-languages();
            }
            settings-clicked => {
                root.settings-clicked();
            }
            set-from(name) => {
                root.set-from(name);
            }
            set-to(name) => {
                root.set-to(name);
            }
        }

        TextInputArea {
            text <=> root.input-text;
            horizontal-stretch: 1;
            vertical-stretch: 1;
            changed => {
                root.text-changed();
            }
        }

        Rectangle {
            height: 4px;
            width: parent.width / 2;
            x: parent.width / 4;
            border-radius: 2px;
            background: AppTheme.border;
        }

        TranslationOutputArea {
            translation-text: root.output-text;
            vertical-stretch: 1;
        }
    }

    FloatingActionButton {
        icon: root.camera-icon;
        x: parent.width - self.width - 24px;
        y: parent.height - self.height - 24px;
        clicked => {
            root.camera-clicked();
        }
    }
}
