import { AppTheme } from "theme.slint";
import { ScrollView, TextEdit } from "std-widgets.slint";

export component TranslationOutputArea inherits ScrollView {
    in property <string> translation-text;
    forward-focus: input;

    VerticalLayout {

        input := TextInput {
            single-line: false;
            text: root.translation-text;
            font-size: 16px;
            wrap: word-wrap;
            read-only: true;
            color: AppTheme.text-primary;
        }
    }
}
